import sqlite3
import os
import json
import time
from typing import Dict, Any, Optional

DATABASE_NAME = "bot_database.db"

def get_connection(db_path: str = DATABASE_NAME) -> sqlite3.Connection:
    """Returns a connection to the SQLite database with dict row factory."""
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn

def init_db(db_path: str = DATABASE_NAME) -> None:
    """Creates the necessary tables if they don't exist."""
    conn = get_connection(db_path)
    cursor = conn.cursor()
    
    # Settings table: Key-Value store for global bot settings
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at REAL NOT NULL
        )
    ''')
    
    # Signals table: Stores LONG/SHORT DCA signals generated by pt_thinker
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS signals (
            symbol TEXT PRIMARY KEY,
            long_level INTEGER NOT NULL DEFAULT 0,
            short_level INTEGER NOT NULL DEFAULT 0,
            updated_at REAL NOT NULL
        )
    ''')
    
    # Price Levels table: Stores the calculated bounding lines (N1-N7) from pt_thinker
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS price_levels (
            symbol TEXT PRIMARY KEY,
            long_levels_json TEXT NOT NULL,
            short_levels_json TEXT NOT NULL,
            updated_at REAL NOT NULL
        )
    ''')
    
    # Process Status: Replaces runner_ready.json, used for IPC readiness
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS process_status (
            process_name TEXT PRIMARY KEY,
            is_ready INTEGER NOT NULL DEFAULT 0,
            last_heartbeat REAL NOT NULL
        )
    ''')

    conn.commit()
    conn.close()

# --- SETTINGS CRUD ---
def set_setting(key: str, value: Any, db_path: str = DATABASE_NAME) -> None:
    conn = get_connection(db_path)
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO settings (key, value, updated_at) 
        VALUES (?, ?, ?)
        ON CONFLICT(key) DO UPDATE SET 
            value=excluded.value, 
            updated_at=excluded.updated_at
    ''', (key, json.dumps(value), time.time()))
    conn.commit()
    conn.close()

def get_setting(key: str, default: Any = None, db_path: str = DATABASE_NAME) -> Any:
    conn = get_connection(db_path)
    cursor = conn.cursor()
    cursor.execute('SELECT value FROM settings WHERE key = ?', (key,))
    row = cursor.fetchone()
    conn.close()
    if row:
        try:
            return json.loads(row['value'])
        except Exception:
            return default
    return default

# --- SIGNALS CRUD ---
def update_signals(symbol: str, long_level: int, short_level: int, db_path: str = DATABASE_NAME) -> None:
    conn = get_connection(db_path)
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO signals (symbol, long_level, short_level, updated_at) 
        VALUES (?, ?, ?, ?)
        ON CONFLICT(symbol) DO UPDATE SET 
            long_level=excluded.long_level, 
            short_level=excluded.short_level,
            updated_at=excluded.updated_at
    ''', (symbol, long_level, short_level, time.time()))
    conn.commit()
    conn.close()

def get_signal(symbol: str, db_path: str = DATABASE_NAME) -> Dict[str, int]:
    conn = get_connection(db_path)
    cursor = conn.cursor()
    cursor.execute('SELECT long_level, short_level FROM signals WHERE symbol = ?', (symbol,))
    row = cursor.fetchone()
    conn.close()
    if row:
         return {"long": row['long_level'], "short": row['short_level']}
    return {"long": 0, "short": 0}

# --- PRICE LEVELS CRUD ---
def update_price_levels(symbol: str, long_levels: list, short_levels: list, db_path: str = DATABASE_NAME) -> None:
    conn = get_connection(db_path)
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO price_levels (symbol, long_levels_json, short_levels_json, updated_at) 
        VALUES (?, ?, ?, ?)
        ON CONFLICT(symbol) DO UPDATE SET 
            long_levels_json=excluded.long_levels_json, 
            short_levels_json=excluded.short_levels_json,
            updated_at=excluded.updated_at
    ''', (symbol, json.dumps(long_levels), json.dumps(short_levels), time.time()))
    conn.commit()
    conn.close()

def get_price_levels(symbol: str, db_path: str = DATABASE_NAME) -> Dict[str, list]:
    conn = get_connection(db_path)
    cursor = conn.cursor()
    cursor.execute('SELECT long_levels_json, short_levels_json FROM price_levels WHERE symbol = ?', (symbol,))
    row = cursor.fetchone()
    conn.close()
    if row:
        try:
            return {
                "long": json.loads(row['long_levels_json']),
                "short": json.loads(row['short_levels_json'])
            }
        except Exception:
            pass
    return {"long": [], "short": []}

# --- PROCESS STATUS CRUD ---
def set_process_ready(process_name: str, is_ready: bool, db_path: str = DATABASE_NAME) -> None:
    conn = get_connection(db_path)
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO process_status (process_name, is_ready, last_heartbeat) 
        VALUES (?, ?, ?)
        ON CONFLICT(process_name) DO UPDATE SET 
            is_ready=excluded.is_ready,
            last_heartbeat=excluded.last_heartbeat
    ''', (process_name, 1 if is_ready else 0, time.time()))
    conn.commit()
    conn.close()

def is_process_ready(process_name: str, stale_seconds: int = 60, db_path: str = DATABASE_NAME) -> bool:
    """Returns True if process marked ready AND heartbeat has been updated recently."""
    conn = get_connection(db_path)
    cursor = conn.cursor()
    cursor.execute('SELECT is_ready, last_heartbeat FROM process_status WHERE process_name = ?', (process_name,))
    row = cursor.fetchone()
    conn.close()
    
    if row:
        ready = bool(row['is_ready'])
        last_beat = float(row['last_heartbeat'])
        if ready and (time.time() - last_beat) <= stale_seconds:
            return True
    return False

if __name__ == "__main__":
    init_db()
    print("Database initialized successfully.")
